env_name: default
colour_specific: ['r', 'g', 'b']
shape_specific: ['square', 'circle', 'triangle']
target_area: -0.8, 0.7 ; 0.25, 0.99
true_norm:
  name: default
  exp: ['Norm', ['Pro', ['Action', 'putdown'], ['Colour', 'g'], ['Shape', 'square'], ['Zone', '1']]]
num_observations: 100
obs_data_set: 1
n: 500 #Length of sequence after discarding warm-up part and splitting in half
m: 10 #Number of sequences after splitting in half- was 10
rf: 0.6
rhat_step_size: 50