from setuptools import find_namespace_packages, setup

setup(
    name='mcmc_norm_learning',
    package_dir={"": "src"},
    packages=find_namespace_packages(where="src"),
    version='0.1.0',
    description='Norm learning via MCMC search over expressions generated by a grammar of norms',
    author='University of Otago',
    license='',
)
