from setuptools import find_namespace_packages, setup

setup(
    name='MCMC-Norm-Learning',
    package_dir={"": "src/mcmc_norm_learning"},
    packages=find_namespace_packages(where="src/mcmc_norm_learning"),
    version='0.1.0',
    description='Norm learning via MCMC search over expressions generated by a grammar of norms',
    author='University of Otago',
    license='',
)
